on: push
name: ðŸš€ Pesona Projetcs
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        server: meayudas1.dyndns.org
        username: github187
        password: DEGKanSLzi2PynrZ
        method: ftp
        port: 12