on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: pesonaprojects/ifantech
    
    - name: ğŸ“‚ Sync files
      uses: pesonaprojects/ifantech
      with:
        server: ftp://89.117.54.16
        username: github187
        password: DEGKanSLzi2PynrZ
